### ISSUE TITLE
Trouble with Install: HTTP error with continuations

### ISSUE THREAD

**Issue by Cauch-BS** [ChangLabSNU/PaperSorter#2]
I'm running this on 

OS: Ubuntu 22.04.04 LTS 
Shell: bash 5.1.16
python: Python 3.10.12
pip: 22.0.2

I'm having trouble with the step `papersorter init`. 
I set up the environmental variables as described, and populated my OldReader with 1583 articles and over 100 starred articles. Upon running `papersorter init` I seem to be getting the following error. 

```
Logged in as myemail@domain.com
Updating feeds...
Processing page 1
Processing page 1
Traceback (most recent call last):
  File "/home/catbase/.local/bin/papersorter", line 5, in <module>
    from PaperSorter.__main__ import main
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/__main__.py", line 36, in <module>
    main()
  File "/home/catbase/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/catbase/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/catbase/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/catbase/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/catbase/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/tasks/init.py", line 53, in main
    update_feeds(True, feeddb, date_cutoff, credential=tor_config,
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/tasks/update.py", line 123, in update_feeds
    retrieve_items_into_db(feeddb, searcher.get_all(limit_items=update_limit), starred=0,
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/tasks/update.py", line 80, in retrieve_items_into_db
    for page, items in enumerate(iterator):
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/providers/theoldreader.py", line 92, in _load_rest
    resp = self._make_search_request(var, limit_items)
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/providers/theoldreader.py", line 77, in _make_search_request
    return self.connection.make_request(
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/contrib/tor.py", line 86, in make_request
    response.raise_for_status()
  File "/home/catbase/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://theoldreader.com/reader/api/0/stream/contents?output=json&s=user%2F-%2Fstate%2Fcom.google%2Freading-list&n=1000&c=1712534399
```

The trouble seems to be with continuations. When I access `https://theoldreader.com/reader/api/0/stream/contents?output=json&s=user%2F-%2Fstate%2Fcom.google%2Freading-list&n=1000&c=`, I get the following json file with 1000 items, as expected. 
![image](https://github.com/ChangLabSNU/PaperSorter/assets/124439247/b80783f2-3073-4309-97d2-8c1986caca5e)

As seen in the screenshot, the continuation appears to be in 1712534399. However when I access `https://theoldreader.com/reader/api/0/stream/contents?output=json&s=user%2F-%2Fstate%2Fcom.google%2Freading-list&n=1000&c=1712534399` I get an `Error: Not Found` message.

![image](https://github.com/ChangLabSNU/PaperSorter/assets/124439247/7984cbb4-4b7a-4fe2-bbe9-27bfad5de4f7)

So the trouble appears to be with the API. However, the [Old Reader API](https://github.com/theoldreader/api) doesn't seem to be actively maintained.

**Comment by hyeshik** [comment]
I tested reproducing the 404 error across both my existing and newly created accounts, but I didn't encounter any issues with either. If you still experience this problem on your account, could you please share more details? This would assist in diagnosing if there might be something specific to our account causing it.

**Comment by Cauch-BS** [comment]
I think the trouble may this condition for training the model, as mentioned by the statement in the README. 

> To train a predictor for your article interests, **ensure your TheOldReader account contains at least 1000 articles**, including at least 100 positively labeled articles marked with stars. Ideally, aim for around 5000 articles with 500 starred items for optimal performance.To train a predictor for your article interests, ensure your TheOldReader account contains at least 1000 articles, including at least 100 positively labeled articles marked with stars. Ideally, aim for around 5000 articles with 500 starred items for optimal performance.

I thought what was meant by my account "containing" 1000 articles was the amount of articles in the the "All Items" tab. I do not remember exactly, but I believe I had nearly 2000 articles in the "All items" tab at the time of originally uploading this issue, and I have 3050 articles currently, as shown below. 

![image](https://github.com/ChangLabSNU/PaperSorter/assets/124439247/62380fbb-b1d5-4311-9675-d8e5a376b1bd)

![image](https://github.com/ChangLabSNU/PaperSorter/assets/124439247/fb2abc98-ad4e-44f9-8e82-8b7834da58c2)

Trying again, I got this error message. The page number at which the error occurs has increased from 1 to 3.  So the error occurs at a later page once the number of articles in the "All items" tab increase, but still does not disappear. 

```
Logged in as cauchybsheen@gmail.com
Updating feeds...
Processing page 1
Processing page 1
Processing page 2
Processing page 3
Traceback (most recent call last):
  File "/home/catbase/.local/bin/papersorter", line 5, in <module>
    from PaperSorter.__main__ import main
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/__main__.py", line 36, in <module>
    main()
  File "/home/catbase/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/catbase/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/catbase/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/catbase/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/catbase/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/tasks/init.py", line 53, in main
    update_feeds(True, feeddb, date_cutoff, credential=tor_config,
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/tasks/update.py", line 123, in update_feeds
    retrieve_items_into_db(feeddb, searcher.get_all(limit_items=update_limit), starred=0,
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/tasks/update.py", line 80, in retrieve_items_into_db
    for page, items in enumerate(iterator):
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/providers/theoldreader.py", line 92, in _load_rest
    resp = self._make_search_request(var, limit_items)
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/providers/theoldreader.py", line 77, in _make_search_request
    return self.connection.make_request(
  File "/home/catbase/.local/lib/python3.10/site-packages/PaperSorter/contrib/tor.py", line 86, in make_request
    response.raise_for_status()
  File "/home/catbase/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://theoldreader.com/reader/api/0/stream/contents?output=json&s=user%2F-%2Fstate%2Fcom.google%2Freading-list&n=1000&c=1699833599
```

I don't understand enough about the code to understand why the page number increased from 1 to 3. I think a source of error might be there were fewer than 1000 articles unread. I manually marked some articles as unread to increase the count to over 1000, but this might not be seen as being "in my account" by the OldReader API.

**Comment by Cauch-BS** [comment]
**Further tests with API** (added)

These tests were done at a later time then my previous comment. 

In the API, this time when I access `https://theoldreader.com/reader/api/0/stream/contents?output=json&s=user%2F-%2Fstate%2Fcom.google%2Freading-list&n=1000`, I get a json file with 1000 items, the same as when I previously uploaded this issue. However, this time when I access the continuation, I get another json file with 1000 items, which is different from when I first posted this issue. I can do this for Page 1, 2, and 3 which seems to be what the code is reflecting. However, on page 3 (shown in the first image below) it says the continuation at `170388799`. However, when I access `https://theoldreader.com/reader/api/0/stream/contents?output=json&s=user%2F-%2Fstate%2Fcom.google%2Freading-list&n=1000&c=1701388799` I get a similar error to when I first uploaded this issue (NOT FOUND error). 

![image](https://github.com/ChangLabSNU/PaperSorter/assets/124439247/ce44c299-9109-458d-997a-6c728f37b165)

![image](https://github.com/ChangLabSNU/PaperSorter/assets/124439247/0161acdf-5b89-4364-9123-0812832c7194)

The change in error message seems to reflect this with the last line of the error message now reading 
``` raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://theoldreader.com/reader/api/0/stream/contents?output=json&s=user%2F-%2Fstate%2Fcom.google%2Freading-list&n=1000&c=1701388799```
which you'll see is different from my last comment where the error message was 
``` raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://theoldreader.com/reader/api/0/stream/contents?output=json&s=user%2F-%2Fstate%2Fcom.google%2Freading-list&n=1000&c=1701388799```

Based on this error, I think it may be possible that the API throws a NOT FOUND error when the number of items is not divisible by 1000, when accessing articles with the condition `n= 1000` in the API. So I marked several articles in my "Unread Articles" as read to test this hypothesis.

Unfortunately, it seems that the API given at `https://theoldreader.com/reader/api/0/stream/contents?output=json&s=user%2F-%2Fstate%2Fcom.google%2Freading-list&n=1000` does not reflect the state the "unread posts" in real time or, alternatively is not the unread posts as all. Marking some items in my inbox as read is not directly reflected in `https://theoldreader.com/reader/api/0/stream/contents?output=json&s=user%2F-%2Fstate%2Fcom.google%2Freading-list&n=1000`.

**Comment by Cauch-BS** [comment]
# Update
Thanks to `@hyeshik` for solving this issue. 

The issue was not with the code itself but rather with the Old Reader API. The issue occured at connection `c 1522415390`, which seems to indicate the API server becomes faulty near 2018/3/30. Unfortunately there were no papers in my reading list near this time, so it was unknown what caused this issue. The only paper in my reading list before 2018 was a paper on 2016 on field potential (here [it](https://www.biorxiv.org/content/10.1101/081125v1?rss=1%2522) is for reference).  

Anyway, the issue could be solved by modifying the behavior `update_feeds` function defined at `__init__.py`. `update_feeds` is defined at`update.py` , and we can cause it to stop before reaching a time when the API server returned an error. 

Currently, `update.py` works by setting `get_full_list` as `True` which means that the `stops_at_no_new_items` is passed as false into `retrieve_items_into_db`. This means (I think) that search stops at the page where there are fewer than 1000 items, meaning that some items in my reading list are dropped. 

`@hysehik` changed the `update_feeds` function at the `__init__.py` as so

```python
### Before
update_feeds(True, feeddb, date_cutoff, credential=tor_config,
                 bulk_loading=True)

### Now
update_feeds(False, feeddb, date_cutoff, credential=tor_config,
                 bulk_loading=True)
```
which was found to resolve the issue.
